version: '3.1'

services:
  redis:
    image: redis
    container_name: redis-master
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --port 6379 --requirepass 123456  --appendonly yes
    volumes:
      - ./redis/data:/data
  mysql:
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: 'isescs'
      MYSQL_PASS: '123456'
    image: "mysql:5.7" 
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/db:/var/lib/mysql"
      - "./mysql/conf:/etc/mysql/conf.d"
      - "./mysql/init:/docker-entrypoint-initdb.d/"

  # PYTHON 项目
  # isescs:
  #   container_name: isescs
  #   build: /root/ISESCS-Python/isescs
  #   restart: always
  #   expose:
  #     - "8000"
  #   volumes:
  #     - /root/ISESCS-Python/isescs:/usr/src/app
  #   command: gunicorn  -c /usr/src/app/gunconfig.py  manage:app
  #   depends_on:
  #     - mysql
  #     - redis
  # ky:
  #   container_name: ky
  #   build: /root/KY_SSEMSystem-Python/ky
  #   restart: always
  #   expose:
  #     - "8000"
  #   volumes:
  #     - /root/KY_SSEMSystem-Python/ky:/usr/src/app
  #   command: gunicorn  -c /usr/src/app/gunconfig.py  manage:app
  #   depends_on:
  #     - mysql
  #     - redis

  php:
    container_name: php
    build: ./php
    restart: always
    expose:
      - "9000"
    volumes:
      - ./nginx/web:/var/www/html
      - "./php/conf.d:/usr/local/etc/php/conf.d"
    depends_on:
      - mysql
      - redis

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/web:/home
    ports:
      - "80:80"
      - "43:433"
    depends_on:
      - isescs
      - ky
      - php
  
  